# Camera to end-effector transformation matrix (eMc)
# This file contains the extrinsic calibration between the camera and the robot end-effector
# 
# The transformation matrix eMc represents the pose of the camera frame 
# with respect to the end-effector frame
#
# Format: 4x4 homogeneous transformation matrix
# [R t]  where R is 3x3 rotation matrix, t is 3x1 translation vector
# [0 1]
#
# NOTE: These are sample values. You need to calibrate your camera-robot setup
# to get the correct transformation matrix for your specific hardware configuration.

eMc:
  rows: 4
  cols: 4
  data: [
    # Row 1: [r11, r12, r13, tx]
    0.0, -1.0, 0.0, 0.0,
    # Row 2: [r21, r22, r23, ty] 
    1.0, 0.0, 0.0, 0.0,
    # Row 3: [r31, r32, r33, tz]
    0.0, 0.0, 1.0, 0.1,
    # Row 4: [0, 0, 0, 1]
    0.0, 0.0, 0.0, 1.0
  ]